import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { Navbar } from "~/components/Navbar";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Genos:wght@600&family=Playfair+Display&family=Roboto+Condensed&display=swap" rel="stylesheet"></link>
        
      </Head>
        <Navbar/>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#ffffff] to-[#ffffff]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 sm:py-8">

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8 flex">
          <div className="items-center text-center"> 
          {/* <img className="h-auto w-[65%] ml-[20%]" src="https://39514401.fs1.hubspotusercontent-na1.net/hubfs/39514401/logosmartoffice.png" alt="" /> */}
            <h1 className="pt-6 text-7xl tracking-tight text-blue sm:text-[6rem] mt-[15%] ml-[5%] font-smart">
              Smart Office
            </h1>
            <p className="text-center text-2xl pt-[7%] font-fancy "> Rentar oficinas desde tu teléfono: fácil y rápido. </p>
          </div>
  
          <img className="h-auto w-30 mr-[65%]" src="https://images.livspace-cdn.com/plain/https://jumanji.livspace-cdn.com/magazine/wp-content/uploads/sites/2/2023/05/23163145/modern-office-interior-design-with-partition-plants.jpg" alt="" />
          </div>

          <h1 className="text-4xl font-smart"> Oficinas Disponibles </h1>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8 flex">

          <img src="https://www.decorilla.com/online-decorating/wp-content/uploads/2023/02/Home-office-inspiration-by-Annie-L.jpg" alt="" />
        
            <Link
              className="flex lg:max-w-[60%] max-w-full flex-col gap-4 bg-white p-4 text-black hover:bg-[#293b5a]/5"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold font-smart"> Oficina Individual</h3>
              <div className="text-lg font-fancy">
              Disfruta de la comodidad y la productividad en nuestra oficina individual, diseñada para ofrecerte un espacio tranquilo y acogedor. Esta oficina cuenta con su propio sistema de climatización para que puedas ajustar la temperatura a tu preferencia y trabajar en un entorno agradable en cualquier temporada.

                Equipada con una computadora de alto rendimiento, todo lo que necesitas para tu trabajo está al alcance de tu mano. 

              Nuestra ubicación privilegiada te brinda acceso a una cafetería cercana, donde puedes disfrutar de bebidas y alimentos deliciosos en tus momentos de descanso.
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-black">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.post.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
